### ISSUE TITLE
M16 confusion in matching outputs to models

### ISSUE THREAD

**Issue by shahbazsyed** [Yale-LILY/SummEval#1]
Hi,
First, thanks for releasing all the model outputs! For model [M16](https://www.aclweb.org/anthology/D19-1323.pdf), I am confused as to which output file relates to which model variation described in the paper.

Files:

![image](https://user-images.githubusercontent.com/4356098/89099710-8f1f6580-d3f1-11ea-8082-a50d2d978f03.png)

Models from the paper:

![image](https://user-images.githubusercontent.com/4356098/89099723-9e061800-d3f1-11ea-9171-359068c5076e.png)

Thanks!

**Comment by muggin** [comment]
Hi @shahbazsyed!

Thanks for the question, the model names are as follows:
`SENECA - outputs_extabs.aligned.jsonl`
`SENECA Sentence Selection Only - outputs_ext.aligned.jsonl`
`SENECA+R_coh+R_ref+R_app - outputs_allrewards.aligned.jsonl`

**Comment by shahbazsyed** [comment]
Thanks!
