### ISSUE TITLE
Code to Reproduce System-Level Metrics

### ISSUE THREAD

**Issue by mingkaid** [Yale-LILY/SummEval#17]
Thanks for generously sharing the annotation data and the evaluation routines! 

Our research team is trying to iterate on the results and add more metrics to the evaluation suite. Meanwhile, we're trying to understand how to produce the system-level metrics reported in the paper, so we can ensure fair comparison. 

Is there any plan to release the process to compute the system-level model scores reported on page 11 of the paper? It'll be great if there was any code, descriptions or metric parameters. 

Thank you again, and I look forward to hearing from you.

**Comment by Alex-Fabbri** [comment]
Hi, 

Thank you for your interest in the work! You can find a link to the code for computing the scores [here](https://github.com/Yale-LILY/SummEval/issues/13#issuecomment-812918298). I will add this to the main page to ensure this is visible. 

Best, 
Alex

**Comment by Alex-Fabbri** [comment]
Hi, 

Thank you for the interest in our work! The scores were primarily computed using the [calc_scores script](https://github.com/Yale-LILY/SummEval/blob/master/evaluation/summ_eval/calc_scores.py), and we provide a sample config file [here](https://github.com/Yale-LILY/SummEval/blob/master/evaluation/examples/basic.config). If you have questions about a specific model/metric or trouble reproducing certain scores, I'm happy to assist!

Best, 
Alex

**Comment by mingkaid** [comment]
Hi Alex,

Thanks for the fast reply! I downloaded and checked the code, and it seems very helpful for comparing metric correlations. 

In addition to this, we're curious about the process to compute these system-level metrics, because the code seems to assume that metrics are already computed. 

I asked this question because I had some difficulties reproducing the automatic metrics on page 11 of the paper. Below is a screenshot of the table
![image](https://user-images.githubusercontent.com/13235754/114214900-ebe4ff80-9932-11eb-825e-3099bf8718d2.png)

For a sanity check, I ran system-level stats metrics with `n_gram=3`, `case=False` and `tokenize=False` on the **human annotated data**, and below are the metrics I got
![image](https://user-images.githubusercontent.com/13235754/114215158-3fefe400-9933-11eb-8634-04e31eed0cf9.png)

Take `Length` metric as an example, the numbers for `Length` and `summary_length` columns are inconsistent across the two tables. 

We're positive that the human annotations are consistent with the paper, but we're curious about the process to create the automatic metrics that can be used to compute correlations. 

Thank you,
Mingkai

**Comment by Alex-Fabbri** [comment]
Hi Mingkai, 

Thank you for the follow-up question! If I understand what you wrote correctly, you are trying to compare the results from Table 4 to the results you obtained on the human-annotated data. However, these are two different subsets - one is on the full dataset and the other is on the set of 100 articles chosen for human evaluation, so these naturally produce different results. Can you please correct me if I misunderstood something?

**Comment by mingkaid** [comment]
That's exactly right, thanks for the clarification! I computed BLEU on the full dataset instead, using the same parameters as provided in `/evaluation/examples/basic.config`. The results are closer to the paper, but there were still small inconsistencies. 

The below code uses `M0` as an illustration. For diagnosis, I directly called the `sacreBLEU` API. 
The corpus-level score was 12.59 on 11490 samples, each using 1 reference, which is 1.17 higher than reported. 
Computing and averaging sentence-level scores led to 11.32, which is 0.1 lower than reported. 
 
I know this is a small difference... However, I'll really appreciate any advice and/or pointers on how to reproduce the scores, because it'll be great if we could control all routines that can lead to inconsistent comparisons down the road. 
 
Below is a screenshot of the routine and results on Jupyter notebook. Let me know if you have any questions or if I did anything wrong. 

![image](https://user-images.githubusercontent.com/13235754/114316549-1620f380-9ad2-11eb-8a09-b762f3b53e1e.png)

![image](https://user-images.githubusercontent.com/13235754/114316564-21741f00-9ad2-11eb-877f-2c353fbf6cfb.png)

**Comment by Alex-Fabbri** [comment]
I will try to run this again on my end. I will likely only get to it in a few days. In the meantime, can you try running both of those with lowercase=True?

**Comment by mingkaid** [comment]
Thanks for agreeing to look into it! I tried `lowercase=True` for both of these, but the BLEU scores stayed the same :/

**Comment by mingkaid** [comment]
BTW the stats metrics are consistent for model `M0`, so I think the dataset is fine

**Comment by mingkaid** [comment]
Hi Fabbri,

Some updates - I managed to produce the system-level Kendall-tau correlations between Data Stats metrics and human judgments, the table shown below. The general trends are similar, but the exact numbers were inconsistent. 

Could you confirm the systems included in the correlation evaluation? From the annotation data, there appears to be no data from M23 - Pegasus - (dynamic mix), which was included in Table 3 of the paper. Could this have affected the correlation results? 

Here's the correlation table I computed: 
![image](https://user-images.githubusercontent.com/13235754/114626878-532be800-9c82-11eb-987d-15b13a4f1e42.png)

Let me know if you have any questions. Thank you!

**Comment by Alex-Fabbri** [comment]
Hi Mingkai, 

For the bleu scores, I repeated the calculations for M0 and am getting the same 11.4270 that I reported in the table. Could you please provide your paired jsonl file (I know you said you checked the dataset statistics, but I just want to confirm it matches exactly) and the result of running pip freeze? 

Yes that would affect the correlations. I just uploaded the file with all annotations, included Pegasus dynamic mix, and metric scores [here](https://drive.google.com/file/d/1d2Iaz3jNraURP1i7CfTqPIj8REZMJ3tS/view?usp=sharing).

**Comment by mingkaid** [comment]
Hi Fabbri,

Thanks for sending the annotations. My paired jsonl file for M0 is [here](https://drive.google.com/file/d/1GA0IFOtbtsMwoE9iQ8m9Cw2guRp_plTt/view?usp=sharing). 

I can confirm that the system-level expert scores are consistent with the paper, and when I correlated the metrics in `metric_scores_11` with the scores, I could reproduce the Kendall Tau coefficients in Table 2. How did you produce the metrics in this dictionary?

**Comment by Alex-Fabbri** [comment]
Hi Mingkai, 

Sorry for the delay. I see there is a difference in the files. In order to do the evaluation more uniformly, we used the same reference for each (rather than the reference provided by the authors, which is what is given in each of the zipped folders), which was from M20, as that seemed to not have any post-processing. We should have made this clearer. I'm attaching a file with references and ids for convenience. 
For producing the metrics in the dictionary, we used the calc-scores script. I'm attaching a version with an extra flag to account for multiple references.
[refs+code.zip](https://github.com/Yale-LILY/SummEval/files/6428607/refs%2Bcode.zip)

**Comment by mingkaid** [comment]
Hi Alex,

Thanks for clarifying! The script and .jsonl file are very helpful. 

One more question - in the full annotation file, are metrics in `metric_scores_11` calculated with 11 references, `metric_scores_6` with 6 references and `metric_scores_1` with 1 reference? Can we assume that the first reference is the official reference?

**Comment by Alex-Fabbri** [comment]
Hi Mingkai, 

Yes, that is correct, and you can assume that the first reference is the official/original reference. I'll close this issue for now, but please open it again if you have any additional questions!
