### ISSUE TITLE
How can I get  "model_annotations.aligned.scored.jsonl"

### ISSUE THREAD

**Issue by vincent1rookie** [Yale-LILY/SummEval#18]
In #13 , You provide a code to calculate kendall correlations for each metrics. However, the code suggests to have a file called `model_annotations.aligned.scored.jsonl` as input. However, I can only find `model_annotations.aligned.jsonl` or `model_annotations.aligned.paired.jsonl`. Neither files have keys like `metric_scores_{args.subset}`. So If I have `--input-file=model_annotations.aligned.jsonl`, I got such error:

Traceback (most recent call last):
  File "system_level_correlations.py", line 87, in <module>
    scores = data[f'metric_scores_{args.subset}']
KeyError: 'metric_scores_1' 

The code I am using is 
[code.zip](https://github.com/Yale-LILY/SummEval/files/6566027/code.zip)

**Comment by carojas13** [comment]
Hi @vincent1rookie 
I am assuming you solve this issue on your own? May I ask what you ended up doing as I am facing pretty much the same issue you outlined above.
