### ISSUE TITLE
sys.exit import missing in supert_metric.py

### ISSUE THREAD

**Issue by zakhan4** [Yale-LILY/SummEval#19]
https://github.com/Yale-LILY/SummEval/blob/1eeb182cf35b2ff9ecaa9833e46e34e7e9056470/evaluation/summ_eval/supert_metric.py#L22

Hello,

When I try to run supert_metric() I get the error: 

> NameError: name 'exit' is not defined

Which is perhaps due to the fact that `from sys import exit` is missing in the file

**Comment by Alex-Fabbri** [comment]
Hi, 
What Python version are you using (and any other environment details would be helpful)? I don't believe it needs to be imported.

**Comment by zakhan4** [comment]
Hi Alex,

I'm trying to run it in google colab notebook, and the python version it shows there is: Python 3.7.10

**Comment by Alex-Fabbri** [comment]
It looks like this is only a problem when running in a colab/ipython notebook. It still prints the export statement to be run, stops the program (albeit with an error), and won't throw an error when the env variable is exported - I'll modify this when I clean up the code next.

**Comment by zakhan4** [comment]
Hi Alex,

When I did specify the python path where summ-eval is installed by running: 

`%env PYTHONPATH="/env/python:/usr/local/lib/python3.7/dist-packages/summ_eval"`

Then I get the error stack trace below. I think it is also related to google colab perhaps. Can you guide me regarding this? Thanks!

`INFO:root:Load pretrained SentenceTransformer: bert-large-nli-stsb-mean-tokens
INFO:root:Did not find a / or \ in the name. Assume to download model from server
INFO:root:Downloading sentence transformer model from https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/bert-large-nli-stsb-mean-tokens.zip and saving it at /root/.cache/torch/sentence_transformers/public.ukp.informatik.tu-darmstadt.de_reimers_sentence-transformers_v0.2_bert-large-nli-stsb-mean-tokens.zip
100%|██████████| 1.24G/1.24G [00:47<00:00, 26.4MB/s]
INFO:root:Load SentenceTransformer from folder: /root/.cache/torch/sentence_transformers/public.ukp.informatik.tu-darmstadt.de_reimers_sentence-transformers_v0.2_bert-large-nli-stsb-mean-tokens.zip
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-30-68a3cce31ee6> in <module>()
      1 import logging
      2 logging.getLogger().setLevel(logging.INFO)
----> 3 rnd_supert = get_supert(mlsum_rnd_sum, mlsum_src)

14 frames
<ipython-input-9-69138e2372af> in get_supert(hypothesis, sources, avg)
    111 
    112 def get_supert(hypothesis, sources, avg=True):
--> 113     metric = supert_metric.SupertMetric()
    114     metric.bert_model = SentenceTransformer('xlm-r-100langs-bert-base-nli-stsb-mean-tokens')
    115     if avg:

/usr/local/lib/python3.7/dist-packages/gin/config.py in gin_wrapper(*args, **kwargs)
   1067       scope_info = " in scope '{}'".format(scope_str) if scope_str else ''
   1068       err_str = err_str.format(name, fn_or_cls, scope_info)
-> 1069       utils.augment_exception_message_and_reraise(e, err_str)
   1070 
   1071   return gin_wrapper

/usr/local/lib/python3.7/dist-packages/gin/utils.py in augment_exception_message_and_reraise(exception, message)
     39   proxy = ExceptionProxy()
     40   ExceptionProxy.__qualname__ = type(exception).__qualname__
---> 41   raise proxy.with_traceback(exception.__traceback__) from None
     42 
     43 

/usr/local/lib/python3.7/dist-packages/gin/config.py in gin_wrapper(*args, **kwargs)
   1044 
   1045     try:
-> 1046       return fn(*new_args, **new_kwargs)
   1047     except Exception as e:  # pylint: disable=broad-except
   1048       err_str = ''

/usr/local/lib/python3.7/dist-packages/summ_eval/supert_metric.py in __init__(self, ref_metric, sim_metric)
     25 class SupertMetric(Metric):
     26     def __init__(self, ref_metric='top15', sim_metric='f1'):
---> 27         self.bert_model = SentenceTransformer('bert-large-nli-stsb-mean-tokens')
     28         self.ref_metric = ref_metric
     29         self.sim_metric = sim_metric

/usr/local/lib/python3.7/dist-packages/summ_eval/sentence_transformers/SentenceTransformer.py in __init__(self, model_name_or_path, modules, device)
     73                 modules = OrderedDict()
     74                 for module_config in contained_modules:
---> 75                     module_class = import_from_string(module_config['type'])
     76                     module = module_class.load(os.path.join(model_path, module_config['path']))
     77                     modules[module_config['name']] = module

/usr/local/lib/python3.7/dist-packages/summ_eval/sentence_transformers/util.py in import_from_string(dotted_path)
     67         raise ImportError(msg)
     68 
---> 69     module = importlib.import_module(module_path)
     70 
     71     try:

/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/usr/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'sentence_transformers'
  In call to configurable 'SupertMetric' (<class 'summ_eval.supert_metric.SupertMetric'>)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`

**Comment by Alex-Fabbri** [comment]
Can you please confirm that PYTHONPATH has been set correctly (make sure "! echo $PYTHONPATH" returns "/env/python:/usr/local/lib/python3.7/dist-packages/summ_eval") and that the folder "/usr/local/lib/python3.7/dist-packages/summ_eval/sentence_transformers" exists?

**Comment by zakhan4** [comment]
Yup the path is correct, and the directory path exists

![image](https://user-images.githubusercontent.com/41992420/122481422-f1b02e80-cfce-11eb-8fb3-3936eafa74ad.png)

**Comment by Alex-Fabbri** [comment]
That's odd - I'll try to figure this out, but for now, as a workaround, you can just add a cell with '% cd /usr/local/lib/python3.7/dist-packages/summ_eval/'

**Comment by zakhan4** [comment]
Hi Alex,

Thanks a  lot. It worked using  the workaround!

Best,
Zohaib
