### ISSUE TITLE
corpus_chrf() got an unexpected keyword argument 'order'

### ISSUE THREAD

**Issue by martin6336** [Yale-LILY/SummEval#24]
The code should get updated in chrfpp_metric.py.
https://github.com/Yale-LILY/SummEval/blob/9f3f008efef142e9514521fbb596c8117b1dcd23/evaluation/summ_eval/chrfpp_metric.py#L33
`sacrebleu.corpus_chrf(hypotheses, [references], char_order=6, word_order=0, beta=3, remove_whitespace=False).score`

**Comment by JeetRoy97** [comment]
Thanks for the suggestion.
Remove .score from the end. @martin6336 

score = sacrebleu.corpus_chrf(summaries, [references], char_order=6, word_order=0, beta=3, remove_whitespace=False)

**Comment by Alex-Fabbri** [comment]
Thanks! Updated.
