### ISSUE TITLE
Data pairing is giving issues

### ISSUE THREAD

**Issue by artidoro** [Yale-LILY/SummEval#4]
Thank you for the great work!

However, the hashes in the output files of the models don't seem to match with the story files.
The data pairing script gives file not found errors, so I investigated and it seems like hashes in the model output filepaths are different from the downloaded story file names.

For example, `c7caf9181c2e94a79d9102da6e11cde48c880aa5.story` cannot be found in the downloaded story files.

**Comment by anjalibshah** [comment]
What was the resolution for this error? I have a similar error:
FileNotFoundError: [Errno 2] No such file or directory: /cnndm/dailymail/stories/92c514c913c0bdfe25341af9fd72b29db544099b.story

**Comment by Alex-Fabbri** [comment]
Hi Anjali, 
Can you please provide some more information on the error (the command) and also check that you are providing the correct path to story_files (absolute vs relative)?

**Comment by anjalibshah** [comment]
Hi Alex - Yes, it was a path issue and is now resolved. Thanks!
