### ISSUE TITLE
Identifying individual annotators

### ISSUE THREAD

**Issue by eryk-mazus** [Yale-LILY/SummEval#41]
Dear SummEval authors.

Thank you for your work. 

I've been exploring the provided expert and crowdsourced annotations and have a question. Does the annotation at the position `i` in the provided list for each summary always corresponds to the same person ?

```
[{'coherence': 2, 'consistency': 1, 'fluency': 4, 'relevance': 2},
 {'coherence': 1, 'consistency': 1, 'fluency': 2, 'relevance': 1},
 {'coherence': 1, 'consistency': 1, 'fluency': 3, 'relevance': 2}]
```
I'd be grateful for answer

**Comment by Alex-Fabbri** [comment]
Hi, 
Thank you for your interest in our work! Yes, the annotation corresponds to the same person for the 4 dimensions.

**Comment by eryk-mazus** [comment]
Thanks for quick reply

**Comment by logan-siyao-peng** [comment]
Another related question: 
Are the 10 "references" of the 100 documents annotated by the same 10 crowd workers and presented in the same fixed order in the list? 
Thank you.
