### ISSUE TITLE
The example doesn't work.

### ISSUE THREAD

**Issue by dominik-schwabe** [Yale-LILY/SummEval#6]
I followed the setup instructions (install, download models, export variables, download basic.config) and ran:
```
calc-scores --config-file=basic.config --metrics "rouge, bert_score" --jsonl-file data.jsonl --output-file rouge_bertscore.jsonl
```
The `data.jsonl` file looks like this:
```
{"reference": "hello world", "summary": "hello world"}
```
It didn't work, so i looked into the source code and changed it to the following:
```
{"reference": "hello world", "decoded": "hello world"}
```
I also had to run `mkdir outputs`.
This did work, but i only got an output for "rouge", but not for "bert_score".
I changed the command to:
```
calc-scores --config-file=basic.config --metrics "rouge,bert_score" --jsonl-file data.jsonl --output-file rouge_bertscore.jsonl
```
since "rouge, bert_score" gets tokenized into ["rouge", " bert_core"] by this code
https://github.com/Yale-LILY/SummEval/blob/b192b27cf6016679439d9e591c12c0b0dd1ae9f3/evaluation/summ_eval/calc_scores.py#L30
Therefore the following check fails:
https://github.com/Yale-LILY/SummEval/blob/b192b27cf6016679439d9e591c12c0b0dd1ae9f3/evaluation/summ_eval/calc_scores.py#L37
After this it still didn't work with the following output:
```
2020-09-14 17:24:48.076345: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib
2020-09-14 17:24:48.076376: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
loading spacy
Reading the input
This many bad lines encountered during loading: 0
Preparing the input
Calculating scores for the rouge metric.
Calculating scores for the bert_score metric.
local variable 'summaries_space' referenced before assignment
An error was encountered with the bert_score metric.
```

**Comment by Alex-Fabbri** [comment]
Thank you for pointing this out! I believe those errors should be fixed now. Let me know if you still encounter any problems.

**Comment by dominik-schwabe** [comment]
thank you, it works now
