### ISSUE TITLE
Data format questions

### ISSUE THREAD

**Issue by danieldeutsch** [Yale-LILY/SummEval#8]
This is very interesting work! Thanks for sharing the data.

I have two questions about the data:
1. Is the original reference summary always the first summary in the `references` list in the jsonl file with the human annotations?
2. Several of the model outputs have multiple aligned files (e.g., M23). Is there an easy way to identify which file contains the summaries which were judged?

**Comment by Alex-Fabbri** [comment]
Hi Daniel, 
Thanks for your interest and sorry for the delay!
1. Yes.
2. I'm attaching the mapping from model number to path: [human_annotation_mapping.txt](https://github.com/Yale-LILY/SummEval/files/5435473/human_annotation_mapping.txt).

**Comment by danieldeutsch** [comment]
Thanks!
